num = int(input('informe um número: '))
n = str(num)
print('analisando o número {}'.format(num))
print('unidade: {}'.format(n[3]))
print('Dezena: {}'.format(n[2]))
print('Centena: {}'.format(n[1]))
print('Milhar: {}'.format(n[0]))