a = input('Digite algo:')
print('O tipo primitvo deste valor é',type(a))
print('Só tem espaços? ', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('Esta em minusculas?', a.islower())
print('Esta em maiusculas?', a.isupper())
print('Esta capitalizada?', a.istitle())