nome = str(input('Escreva um nome:')).strip()
mai = nome.upper()
min = nome.lower()
totl = len(nome)-nome.count(' ')
pri = nome.split()
prime = (pri [0])
second = (pri[1])
print ('em letras maisculas é {} e letras minusculas é {}, tem um total de {} letras o primeiro nome é {} e o segundo {}'.format(mai,min,totl,prime,second))
print('Seu primeiro nome tem {} letras '.format(nome.find(' ')))
